[theme]
base                = "dark"
primaryColor        = "#F85149"
backgroundColor     = "#0D1117"
secondaryBackgroundColor = "#161B22"
textColor           = "#E6EDF3"
font                = "sans serif"
